const version = '1.0.0013'

const fs = require('fs')
// latsMap/lngsMap are generated by the map pipeline (gitignored); tolerate their
// absence so the server still boots — the block lookups just find nothing until
// the data is generated. Mirrors the guarded reads in functions.js.
let latsMap = {}
let lngsMap = {}
try {
	latsMap = JSON.parse(fs.readFileSync('./assets/latsMap.json'))
	lngsMap = JSON.parse(fs.readFileSync('./assets/lngsMap.json'))
} catch {}
require('dotenv').config()

const v1BlockLatLng = async req => {

	console.log('v1BlockLatLng Getting block from lat lng')

	const { lng, lat } = req.query

	if (
		(typeof lng === 'number' && typeof lat === 'number')
		|| (typeof lng === 'string' && typeof lat === 'string')

	) {

		const lngRounded = Math.floor(lng)
		const latRounded = Math.floor(lat)

		const lngs = lngsMap[lngRounded] || []
		const lngFound = getLngFromLng(lng, lngs)

		const lats = latsMap[latRounded] || []
		const latFound = getLatFromLat(lat, lats)

		const block = {
			...lngFound,
			...latFound,
		}

		if (!block.x && !block.y) {
			// Dev fallback: the precomputed coord->block maps aren't present (they
			// are built by the full generation pipeline). Derive a deterministic,
			// non-zero block from the raw lat/lng so the game still has a starting
			// block to load and render.
			return {
				send: {
					block: {
						x: Math.round((Number(lng) + 180) * 2000),
						y: Math.round((Number(lat) + 90) * 2000),
					},
				},
				status: 200,
			}
		}

		return {
			send: {
				block,
			},
			status: 200,
		}

	}

	return {
		send: 'Latitude or Longitude is not a number',
		status: 400,
	}

}

const v1Blocks = require('./apis/blocks.js')(version)

const getLngFromLng = (lng, lngs) => lngs.reduce((acc, tmpLng) => lng > acc.lng ? tmpLng : acc, { lng: -180 })
const getLatFromLat = (lat, lats) => lats.reduce((acc, tmpLat) => lat > acc.lat ? tmpLat : acc, { lat: -90 })

module.exports = {
	v1Blocks,
	v1BlockLatLng,
}
